enhance(deployment): add payload metadata from github
go-vela/types pull request #117
Opened 2020-11-30 21:19 UTC by JordanSussman

Adds the `DeployPayload` field to the `Build` struct to track the payload passed along from GitHub.

xref: https://github.com/go-vela/community/issues/89

2020-12-02 18:33 UTC, davidvader approved these changes
LGTM

2020-12-04 13:43 UTC, jbrockopp requested changes

2020-12-04 13:43 UTC, jbrockopp commented on raw/map.go
> +// Value returns the map in JSON format
Hate to be nit-picky but could we get `.` to follow this comment?

```suggestion
// Value returns the map in JSON format.
```

2020-12-04 13:43 UTC, jbrockopp commented on raw/map.go
> +// Scan decodes the JSON string into map[string]string
Hate to be nit-picky but could we get `.` to follow this comment?

```suggestion
// Scan decodes the JSON string into map[string]string.
```

2020-12-04 17:17 UTC, jbrockopp approved these changes
LGTM

2020-12-07 14:11 UTC, kneal approved these changes
LGTM 🐬

2020-12-07 14:11 UTC, merged