Feat/buildtimeoutmin
go-vela/types pull request #120
Opened 2020-12-07 20:11 UTC by KellyMerrick

2020-12-07 22:09 UTC, matt-fevold requested changes

2020-12-07 22:09 UTC, matt-fevold commented on constants/limit.go
> +	// BuildTimeoutMax defines the maximum value in minutes for repo build timeout.
Comment doesn't match varaible

2020-12-08 00:12 UTC, wass3r approved these changes

2020-12-08 14:08 UTC, matt-fevold approved these changes

2020-12-08 16:18 UTC, merged