Fix Unmarshal Panic
go-vela/types pull request #185
Opened 2021-06-18 15:45 UTC by GregoryDosh

Identified bug in https://github.com/go-vela/community/issues/300 which results in a panic due to the assumption that the strings are split into a key/value pair on `=` which isn't always true, as evidence by this contrived data example.

I'm not sure of a contrived example for the JSON case, but I'm assuming it could happen too, so I fixed it in both the YAML and JSON Unmarshal functions. if you comment out the length checks but leave the step test and run it you'll see the same panic as in https://github.com/go-vela/community/issues/300

2021-06-23 16:07 UTC, wass3r requested changes
couple of tweaks.. can you change the title of the PR to follow https://github.com/go-vela/types/blob/master/.github/CONTRIBUTING.md#development (it's a bit buried, but it's under the "Open a pull request!" heading).

2021-06-23 16:07 UTC, wass3r commented on raw/map.go
> +			if len(kvPair) != 2 {
could add something along the lines of https://github.com/go-vela/types/blob/8396842ec2d0693ae1f97f5372debf9577426117/yaml/ulimit.go#L62 here to silence the linter. i don't think we need to make it a constant.

2021-06-23 16:07 UTC, wass3r commented on raw/map.go
> +			if len(kvPair) != 2 {
could add something along the lines of https://github.com/go-vela/types/blob/8396842ec2d0693ae1f97f5372debf9577426117/yaml/ulimit.go#L62 here to silence the linter. i don't think we need to make it a constant.

2021-06-24 03:54 UTC, wass3r commented
Thanks for the changes. I think this makes sense. My only other suggestion would be to add a test case closer to where the fix was a applied, ie. in `/raw/map_test.go`.

2021-06-24 15:44 UTC, GregoryDosh commented
@wass3r I can take a look at updating the tests to be more localized and specific. I need to attach the debugger and figure out why panic (and the tests) weren't triggering when the code was more localized. It might shed more light on other aspects that could be spruced up.

2021-06-24 15:57 UTC, wass3r commented
@GregoryDosh sounds good - thanks! i know the current test added in the other spot covers the fix, but localizing the test will make the fixed code a bit more portable and help prevent regression. however, it _does seem_ a bit nitpicky and i'm good with approving this otherwise - thanks again for the contribution!

2021-06-24 15:58 UTC, wass3r approved these changes

2021-06-24 16:24 UTC, GregoryDosh commented
I've found a more localized test that triggers the panic in the unmarshalling for string slice maps. It feels odd though that we're hitting into that given the input data. There might be something higher level happening here that could be investigated but at least this prevents an occasional panic.

2021-06-24 16:30 UTC, wass3r approved these changes

2021-06-24 17:55 UTC, jbrockopp approved these changes
LGTM

2021-06-24 17:55 UTC, merged