feat(repo): add pipeline type to structs
go-vela/types pull request #188
Opened 2021-07-08 19:58 UTC by kneal

Changes included in PR:

- add new pipeline type field to repo library struct
- add new pipeline type field to repo database struct

Co-authored-by: @JordanSussman

2021-07-09 01:59 UTC, JordanSussman requested changes
initial feedback

2021-07-09 01:59 UTC, JordanSussman commented on constants/repo.go
> +	PipelineTypeGo = "yaml"
This should be updated to `go` or `golang`.

2021-07-09 01:59 UTC, JordanSussman commented on constants/repo.go
> +	PipelineTypeStarlark = "yaml"
This should be updated to `starlark`.

2021-07-09 01:59 UTC, JordanSussman commented on database/repo.go
> +	// }
This should be uncommented.

2021-07-09 01:59 UTC, JordanSussman commented on library/repo.go
> +	PipelineType: %s,
Need to fix indentation to align with the other code.

2021-07-09 01:59 UTC, JordanSussman commented on library/repo_test.go
> +	PipelineType: %s,
Need to fix indentation to align with the other code.

2021-07-15 01:23 UTC, wass3r approved these changes

2021-07-19 14:14 UTC, jbrockopp approved these changes
LGTM

2021-07-20 15:10 UTC, JordanSussman approved these changes
LGTM

2021-07-20 15:23 UTC, merged