feat(environment): add pusher name and email for tag events
go-vela/types pull request #207
Opened 2021-11-05 19:50 UTC by ecrupper

Currently, when a user drafts a release, the build author remains the person who last committed to the repository. We want to keep this, but we also want to know who tagged the release. Therefore, these additional fields in tandem with the server setting these values from GitHub will expose that information as environment variables.

2021-11-09 14:04 UTC, jbrockopp requested changes
Requested some changes but I also have a question.

We're adding two new fields to the `library.Build{}` type:

* `PusherName`
* `PusherEmail`

Do we also need to add these fields to the `database.Build{}` type?

https://github.com/go-vela/types/blob/911ffbea2e427883ccca2cc3f3769fdae75e0946/database/build.go#L32-L63

2021-11-09 14:04 UTC, jbrockopp commented on library/build.go
> +}
Looks like comments are missing here.

To show an example of what those comments may look like:

https://github.com/go-vela/types/blob/911ffbea2e427883ccca2cc3f3769fdae75e0946/library/build.go#L415-L426

2021-11-09 14:04 UTC, jbrockopp commented on library/build.go
> +}
Looks like comments are missing here.

To show an example of what those comments may look like:

https://github.com/go-vela/types/blob/911ffbea2e427883ccca2cc3f3769fdae75e0946/library/build.go#L428-L439

2021-11-09 14:04 UTC, jbrockopp commented on library/build.go
> +}
Looks like comments are missing here.

To show an example of what those comments may look like:

https://github.com/go-vela/types/blob/911ffbea2e427883ccca2cc3f3769fdae75e0946/library/build.go#L792-L803

2021-11-09 14:04 UTC, jbrockopp commented on library/build.go
> +}
Looks like comments are missing here.

To show an example of what those comments may look like:

https://github.com/go-vela/types/blob/911ffbea2e427883ccca2cc3f3769fdae75e0946/library/build.go#L805-L816

2021-11-09 16:04 UTC, ecrupper commented
> Requested some changes but I also have a question.
> 
> We're adding two new fields to the `library.Build{}` type:
> 
> * `PusherName`
> * `PusherEmail`
> 
> Do we also need to add these fields to the `database.Build{}` type?
> 
> https://github.com/go-vela/types/blob/911ffbea2e427883ccca2cc3f3769fdae75e0946/database/build.go#L32-L63

Yeah that was something I was discussing with @davidvader . Since we are adding the field to the library type, it would make sense to be consistent with the database. However, since their use is purely for creating some environment variables, I figured I'd get some more feedback on whether it would be wise to include it in the database. Looking at code such as this: [https://github.com/go-vela/types/blob/911ffbea2e427883ccca2cc3f3769fdae75e0946/library/build.go#L132-L133](url) where we aren't ever storing those values on our end, I thought it would be worth discussing. Further, taking a look at @JordanSussman 's comments on the related server PR for this (draft - [https://github.com/go-vela/server/pull/527](url)), it may not even be the right approach at all. Perhaps using sender, which we already store, is the right way to go about this. However, finding the email may be tricky. Would love to hear more thoughts!

2021-11-15 15:48 UTC, ecrupper commented
Closing this PR in favor of utilizing the `sender` field and not including the `TAGGER_EMAIL` since we cannot reliable get that information from GitHub webhook.

2021-11-15 15:48 UTC, closed without merging