feat(stage): add environment field
go-vela/types pull request #215
Opened 2021-12-07 19:58 UTC by ecrupper

[Related Issue](https://github.com/go-vela/community/issues/420)

Adding an environment map to the stage environment. I've worked on the server functionality and did not end up using the MergeEnv function that I copied over from `step`, but I figured adding the same function to the stage object would be good for future use if the need were to arise.

2021-12-20 17:19 UTC, jbrockopp requested changes

2021-12-20 17:19 UTC, jbrockopp commented on pipeline/stage.go
> +		Steps       ContainerSlice    `json:"steps,omitempty" yaml:"steps,omitempty"`
Can we align the `yaml` struct field tags here?

```suggestion
		Done        chan error        `json:"-"                     yaml:"-"`
		Environment map[string]string `json:"environment,omitempty" yaml:"environment,omitempty"`
		Name        string            `json:"name,omitempty"        yaml:"name,omitempty"`
		Needs       []string          `json:"needs,omitempty"       yaml:"needs,omitempty"`
		Steps       ContainerSlice    `json:"steps,omitempty"       yaml:"steps,omitempty"`
```

2021-12-20 17:19 UTC, jbrockopp commented on pipeline/stage.go
> +	// return true if the container is nil
I think the comment here has a typo i.e. ~`container`~

```suggestion
	// return true if the stage is nil
```

2021-12-20 17:19 UTC, jbrockopp commented on pipeline/stage.go
> +	// return false if any of the ruletype is provided
I think the comment here has a typo i.e. ~`ruletype`~

```suggestion
	// return false if any of the stage fields are not empty
```

2021-12-20 17:19 UTC, jbrockopp commented on pipeline/stage.go
> +	// check if the container is empty
I think the comment here has a typo i.e. ~`container`~

```suggestion
	// check if the stage is empty
```

2021-12-20 17:19 UTC, jbrockopp commented on pipeline/stage.go
> +		return fmt.Errorf("empty environment provided for container %s", s.Name)
I think the error message here has a typo i.e. ~`container`~

```suggestion
		return fmt.Errorf("empty environment provided for stage %s", s.Name)
```

2021-12-20 17:19 UTC, jbrockopp commented on pipeline/stage.go
> +		// set or update the container environment variable
I think the comment here has a typo i.e. ~`container`~

```suggestion
		// set or update the stage environment variable
```

2021-12-20 17:19 UTC, jbrockopp commented on yaml/stage.go
> +		Steps       StepSlice          `yaml:"steps,omitempty" json:"steps,omitempty" jsonschema:"required,description=Sequential execution instructions for the stage.\nReference: https://go-vela.github.io
Can we align the struct field tags here?

```suggestion
		Environment raw.StringSliceMap `yaml:"environment,omitempty" json:"environment,omitempty" jsonschema:"description=Provide environment variables injected into the container environment.\nReference: https://go-vela.github.io/docs/reference/yaml/stages/#the-environment-tag"`
		Name        string             `yaml:"name,omitempty"        json:"name,omitempty"        jsonschema:"minLength=1,description=Unique identifier for the stage in the pipeline.\nReference: https://go-vela.github.io/docs/reference/yaml/stages/#the-name-tag"`
		Needs       raw.StringSlice    `yaml:"needs,omitempty,flow"  json:"needs,omitempty"       jsonschema:"description=Stages that must complete before starting the current one.\nReference: https://go-vela.github.io/docs/reference/yaml/stages/#the-needs-tag"`
		Steps       StepSlice          `yaml:"steps,omitempty"       json:"steps,omitempty"       jsonschema:"required,description=Sequential execution instructions for the stage.\nReference: https://go-vela.github.io/docs/reference/yaml/stages/#the-steps-tag"`
```

2021-12-20 17:19 UTC, jbrockopp commented on yaml/stage.go
> +	// check if the step container is empty
I think the comment here has a typo i.e. ~`container`~

```suggestion
	// check if the stage environment is empty
```

2021-12-20 17:19 UTC, jbrockopp commented on yaml/stage.go
> +		return fmt.Errorf("empty environment provided for step %s", s.Name)
I think the error message here has a typo i.e. ~`step`~

```suggestion
		return fmt.Errorf("empty environment provided for stage %s", s.Name)
```

2021-12-20 17:19 UTC, jbrockopp commented on yaml/stage.go
> +		// set or update the step environment variable
I think the error message here has a typo i.e. ~`step`~

```suggestion
		// set or update the stage environment variable
```

2021-12-21 16:25 UTC, jbrockopp requested changes
Could we add a test here for this YAML functionality?

Specifically, with regards to unmarshalling YAML for `stages` with an `environment` block?

I think updating the existing test would work so here are the locations for reference:

https://github.com/go-vela/types/blob/87c103bb6341d1e4d8c9655631bb8cbf059def76/yaml/stage_test.go#L173

https://github.com/go-vela/types/blob/feat/add-stage-environment/yaml/testdata/stage.yml

2021-12-21 16:58 UTC, jbrockopp approved these changes
LGTM

2021-12-22 01:51 UTC, JordanSussman approved these changes

2021-12-22 01:58 UTC, merged