enhance(repo): add repo topics to repo object + build environment
go-vela/types pull request #285
Opened 2023-04-06 20:27 UTC by ecrupper

Part of the effort for https://github.com/go-vela/community/issues/774

Injects repo topics into the environment as well as saves them in the database.

2023-04-06 20:52 UTC, wass3rw3rk requested changes
one minor typo

2023-04-06 20:52 UTC, wass3rw3rk commented on database/repo.go
> +	// User type has Topics field provided that exceeds the database limit.
```suggestion
	// Repo type has Topics field provided that exceeds the database limit.
```

2023-04-07 12:10 UTC, wass3rw3rk approved these changes

2023-04-07 14:54 UTC, timhuynh94 approved these changes

2023-04-07 14:57 UTC, merged