feat(yaml/secret): adding pull tag to secrets to create a lazy secrets ability
go-vela/types pull request #312
Opened 2023-09-07 15:30 UTC by claire1618

Here's the issue: https://github.com/go-vela/community/issues/196

The changes here add a tag "pull" to secrets that can be set to either "always" or "on_start". 

Setting pull to on_start ensures that secrets are pulled when the underlying step starts, and setting the pull to always is the current behavior of pulling secrets at the beginning of the build.

Example:
```
secrets:
  - name: foo
    key: go-vela/docs/foo
    engine: native
    type: repo
    pull: on_start
```

2023-10-23 18:12 UTC, ecrupper requested changes

2023-10-23 18:12 UTC, ecrupper commented on pipeline/secret_test.go
> +				Pull:        "build_start",
These secret plugin blocks will still be `pull: always`, as that is referring to the vault image

2023-10-23 18:12 UTC, ecrupper commented on yaml/secret.go
> +		Pull   string `yaml:"pull,omitempty"   json:"pull,omitempty" jsonschema:"default=always,description=Where to pull in secrets from storage backend."`
```suggestion
		Pull   string `yaml:"pull,omitempty"   json:"pull,omitempty" jsonschema:"default=build_start,description=When to pull in secrets from storage backend."`
```

2023-10-24 16:20 UTC, ecrupper approved these changes

2023-10-24 18:44 UTC, cognifloyd approved these changes

2023-10-24 20:11 UTC, merged