enhance(secret): use allow event system
go-vela/types pull request #341
Opened 2024-01-03 22:12 UTC by ecrupper

It will be helpful to share the same structure for allowed events for both repos and secrets.

2024-01-03 22:21 UTC, wass3rw3rk requested changes
first pass..

also, i didn't verify, but is checkEvents() actually unused as the linter claims? we can remove, if so.

2024-01-03 22:21 UTC, wass3rw3rk commented on library/actions/schedule.go
> +	Run *bool `json:"created"`
```suggestion
	Run *bool `json:"run"`
```

2024-01-03 22:21 UTC, wass3rw3rk commented on library/actions/schedule.go
> +// with the deploy event webhook from the SCM.
```suggestion
// with the schedule event webhook from the SCM.
```

2024-01-03 22:25 UTC, ecrupper commented
> first pass..
> 
> also, i didn't verify, but is checkEvents() actually unused as the linter claims? we can remove, if so.

The linter really does have its moments

2024-01-05 16:00 UTC, wass3rw3rk submitted a review, later dismissed

2024-01-05 18:12 UTC, wass3rw3rk approved these changes

2024-01-05 18:25 UTC, merged