feat(rulesets): add support for PR labeled events
go-vela/types pull request #361
Opened 2024-03-12 17:36 UTC by wsan3

Add support for pull request events that have an action of [labeled](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=labeled#pull_request)

GitHub [issue #913](https://github.com/go-vela/community/issues/913)
GitHub [ideas #768](https://git.target.com/orgs/vela/projects/36/views/1?filterQuery=win+san&pane=issue&itemId=19205)

2024-03-13 14:14 UTC, ecrupper requested changes
Looks great. One typo I noticed and that's it

2024-03-13 14:14 UTC, ecrupper commented on library/actions/pull.go
> +	// return zero value if Pull type or Reopened field is nil
```suggestion
	// return zero value if Pull type or Labeled field is nil
```

2024-03-25 14:45 UTC, ecrupper commented on pipeline/ruleset.go
> +		Label    string   `json:"label,omitempty"   yaml:"label,omitempty"`
Thoughts on extending this rule to include other `pull_request` events, which would result in passing in a slice of label strings? So if a PR has labels `bug` and `v2`, we'd pass in a label set of `[]string{"bug", "v2"}`?

2024-04-02 14:24 UTC, plyr4 requested changes

2024-04-02 14:24 UTC, plyr4 commented on pipeline/ruleset.go
> +			if match {
@wsan3 can we fix this linter warning? 
```suggestion

			if match {
```

2024-04-02 14:58 UTC, plyr4 approved these changes

2024-04-02 15:21 UTC, wass3rw3rk approved these changes

2024-04-02 15:37 UTC, merged